services:
  redis-node1:
    image: redis:latest
    container_name: can_redis_node1
    command: >
      redis-server --appendonly yes --port 6379 --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7000:6379"
    networks:
      - redis-cluster

  redis-node2:
    image: redis:latest
    container_name: can_redis_node2
    command: >
      redis-server --appendonly yes --port 6380 --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7001:6380"
    networks:
      - redis-cluster

  redis-node3:
    image: redis:latest
    container_name: can_redis_node3
    command: >
      redis-server --appendonly yes --port 6381 --cluster-enabled yes
      --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7002:6381"
    networks:
      - redis-cluster


networks:
  redis-cluster:
    driver: bridge
